dataNexus:
  image: sonatype/nexus
  command: "tail -f /dev/null"
  volumes:
    - "/sonatype-work"

nexus:
  image: sonatype/nexus
  ports: 
    - "8081:8081"
  volumes_from:
    - dataNexus

jenkins:
  build: jenkins
  ports: 
    - "8080:8080"
    - "5000:5000"

dockerRegistry:
   image: "registry:2"
   ports:
    - "5001:5000"

