version: '2'
services:
  datanexus:
    build: "data"
    volumes:
     - "/sonatype-work"
    restart: always
  datajenkins:
    build: "data"
    volumes:
     - "/var/jenkins_home"
    restart: always
  dataregistry:
    build: "data"
    volumes:
     - "/tmp/registry"
    restart: always
  nexus:
    build: "nexus"
    ports:
      - "8081"
    volumes_from:
      - "datanexus"
    restart: always

  jenkins:
    build: "jenkins"
    ports:
      - "8080"
      - "50000"
    volumes_from:
      - "datajenkins"
    restart: always
  sonarqube:
    build: "sonarqube"
    ports:
     - "9000"
     - "5432"
    environment:
     - SONARQUBE_JDBC_URL:"jdbc:postgresql://localhost:5432/sonar"
     - SONARQUBE_JDBC_USERNAME:"ci"
     - SONARQUBE_JDBC_PASSWORD:"ci-pass"
    restart: always

  sonarqubedb:
    image: postgres
    environment:
     - POSTGRES_USER:"ci"
     - POSTGRES_PASSWORD:"ci-pass"
  registry:
     build: "registry"
     ports:
      - "5000"
     volumes_from:
      - "dataregistry"
     restart: always

  swagger:
     image: "sjeandeaux/docker-swagger-ui"
     ports:
      - "8888"
     restart: always
  ldap:
     build: "ldpa"
     restart: always

  haproxy:
     build: "haproxy"
     ports:
      - "80:80"
      - "8666:8666"
     links:
      - "jenkins:jenkins"
      - "nexus:nexus"
      - "sonarqube:sonarqube"
      - "swagger:swagger"
