data:
  build: "data"
  volumes:
   - "/sonatype-work"

nexus:
  image: "sonatype/nexus"
  ports: 
    - "8081:8081"
  volumes_from:
    - "data"

jenkins:
  build: "jenkins"
  ports: 
    - "8080:8080"
    - "5000:5000"

dockerRegistry:
   image: "registry:2"
   ports:
    - "5001:5000"

swagger:
   image: "sjeandeaux/docker-swagger-ui"
   ports:
    - "8888:8888"

