data:
  build: "data"
  volumes:
   - "/sonatype-work"
   - "/var/jenkins_home"
  restart: always

nexus:
  image: "sonatype/nexus"
  ports: 
    - "8081:8081"
  volumes_from:
    - "data"
  restart: always

jenkins:
  build: "jenkins"
  environment:
    JAVA_OPTS: "-Djava.awt.headless=true"
  ports: 
    - "8080:8080"
    - "50000:50000"
  volumes_from:
    - "data"
  restart: always

dockerRegistry:
   image: "registry:2"
   ports:
    - "5000:5000"
   restart: always

swagger:
   image: "sjeandeaux/docker-swagger-ui"
   ports:
    - "8888:8888"
   restart: always

